<?php

$s = '<h1>MicroFramework installation finished</h1>';
$s.= '<p>You have successfully installed a new MicroFramework project.</p>'.N;

$s.= '<p>An example of a view variable as defined in the controller: ' . $this->someVar . '.</p>'.N;

$this->setSlot('pagetitle', null);

$this->setSlot('meta.description', 'MicroFramework installation finished');
$this->setSlot('meta.keywords', 'microframework, new project, installation');
$this->setSlot('meta.author', 'MicroFramework');
$this->setSlot('meta.revisit-after', '1 month');

$this->setSlot('content', $s);

print($this->render('base/page.phtml'));