<?php

$form = $this->defaultSlot('form', null);
$field = $this->defaultSlot('form.field', null);
if (!$field) return;

if (!$form->getField($field)->getOptions()) return;
$attributes = '';
if ($form->getFields($field)->getAttributes()) {
    foreach($form->getField($field)->getAttributes() as $attr_name => $attr_val) {
        $attributes.= ' '.$attr_name.'="'.$attr_val.'"';
    }
}

$s = '';
$s.= '<div class="formfield-container">'.N;
$s.= '<select name="'.$field.'"'.$attributes.'>'.N;
foreach($form->getField($field)->getOptions() as $value => $text) {
    $selected = null;
    if ($form->getField($field)->getInitial() === $value) {
        $selected = ' selected="selected"';
    }
    $s.= '  <option value="'.$value.'"'.$selected.'>'.$text.'</option>'.N;
}
$s.= '</select>'.N;
if (!$form->getField($field)->isValid()) {
    $s.= '<img class="select-error" src="/style/error.png" alt="'.$form->getFields($field)->getFirstError().'" title="'.$form->getField($field)->getFirstError().'">'.N;
}
$s.= '</div>'.N;

print($s);